- id: de-ai-agent
  name: Remove AI pollution from commit messages
  description: Removes Co-Authored-By AI attribution and branding footers from commit messages
  entry: de-ai-agent
  language: python
  stages: [commit-msg]
  default_install_hook_types: [commit-msg]
  pass_filenames: false
